# version: "3"
services:

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: gapi_front
    container_name: gapi_front_c
    ports:
      - "8080:80"
    volumes:
      - ./front:/var/www/html/
      - storage:/var/www/html/storage
    # command: [ 'apache2ctl', '-D', 'FOREGROUND' ]

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: gapi_back
    container_name: gapi_back_c
    ports:
      - "5050:5000"
    volumes:
      - ./back:/app
      - storage:/app/storage
    command: python app.py

  back2:
    image: gapi_back
    container_name: gapi_our_back_c
    ports:
      - "5051:5000"
    volumes:
      - ./back:/app
      - storage:/storage
    command: python our_app.py


volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      device: ./storage
      o: bind